spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm99627
    password: 051298
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    supportedSubMethods: "get"
  api-docs:
    enabled: true