spring:
  datasource:
    url: jdbc:mariadb://${DB_DESENV_SERVER:localhost}:${DB_DESENV_PORT:3306}/${DB_DESENV_NAME:analise-spring-motos}?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update